
security:
  basic:
    enabled: false
  user:
    name: root
    password: zscome
server:
  port: 8081


spring:
  application:
    name: udip-manager

eureka:
  instance:
    prefer-ip-address: true
    hostname: 172.16.43.154
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:zscome@172.16.43.154:9090/eureka
    enabled: true
